# Nixpacks configuration for Railway
[phases.build]
dependsOn = ["install"]

[phases.install]
cmds = [
  "npm config set fetch-retry-mintimeout 20000",
  "npm config set fetch-retry-maxtimeout 120000", 
  "npm config set fetch-timeout 300000",
  "npm ci --only=production --no-audit --no-fund"
]

[phases.build]
cmds = ["echo 'No build step required'"]

[start]
cmd = "node --max-old-space-size=512 --expose-gc --optimize-for-size server.js"

[variables]
NODE_ENV = "production"
RAILWAY = "true"
PORT = "8080"
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "false"
