# Render.com deployment configuration

[[services]]
type = "web"
name = "tailoring-whatsapp-bot"
env = "node"
plan = "starter"
buildCommand = "npm cache clean --force && npm ci --no-audit --no-fund --prefer-offline --timeout=300000 && chmod +x start.sh"
startCommand = "./start.sh"
healthCheckPath = "/healthz"

[services.envVars]
NODE_ENV = "production"
RENDER = "true"
SEND_DELAY_MS = "1000"
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "false"
PUPPETEER_CACHE_DIR = "/opt/render/project/src/.puppeteer_cache"
PUPPETEER_EXECUTABLE_PATH = "/usr/bin/google-chrome-stable"
NODE_OPTIONS = "--max-old-space-size=256"
