services:
  - type: web
    name: tailoring-whatsapp-bot
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: NODE_OPTIONS
        value: "--max-old-space-size=512"
